# Generated by Django 2.2.2 on 2022-01-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesdeReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Cliente')),
                ('diasestadia', models.IntegerField(verbose_name='Dias de estadia')),
                ('numerohabitaciones', models.IntegerField(verbose_name='Numero de habitacion')),
                ('montopordia', models.IntegerField(verbose_name='Precio por dia')),
                ('metodopago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], max_length=20, verbose_name='Tipo de Pago')),
                ('tipodereserva', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('eliminado', 'Eliminado')], max_length=20, verbose_name='Reserva')),
            ],
        ),
    ]
